Document: git-reaper
Title: Debian git-reaper Manual
Author: <insert document author here>
Abstract: This manual describes what git-reaper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-reaper/git-reaper.sgml.gz

Format: postscript
Files: /usr/share/doc/git-reaper/git-reaper.ps.gz

Format: text
Files: /usr/share/doc/git-reaper/git-reaper.text.gz

Format: HTML
Index: /usr/share/doc/git-reaper/html/index.html
Files: /usr/share/doc/git-reaper/html/*.html
