isar:
  url: git@github.com:vj-kumar/isar.git
  upstream: https://github.com/ilbers/isar.git
  mail: isar-users@googlegroups.com

jailhouse:
  url: git@github.com:vj-kumar/jailhouse.git
  upstream: https://github.com/siemens/jailhouse.git
  mail: jailhouse-dev@googlegroups.com

jailhouse-images:
  url: git@github.com:vj-kumar/jailhouse-images.git
  upstream: https://github.com/siemens/jailhouse-images.git
  mail: jailhouse-dev@googlegroups.com

linux-shakti:
  url: git@github.com:vj-kumar/linux-shakti.git
  upstream: https://github.com/torvalds/linux.git
  mail: shakti-sw@googlegroups.com

opensbi:
  url: git@github.com:vj-kumar/opensbi.git
  upstream: https://github.com/riscv/opensbi.git

uboot:
  url: git@github.com:vj-kumar/u-boot.git
  upstream: https://github.com/u-boot/u-boot.git
